### ISSUE TITLE
Paginate

### ISSUE THREAD

**Issue by Korogba** [spatie/searchindex#6]
Hi. Nice and easy to use implementation of elasticsearch. How can you implement pagination on the results consistent with laravel ? Do you need to do that in laravel?

**Comment by tandasima** [comment]
Yes you can do that in Laravel. Since you implemented getSearchableId() in your model, just retrieve each data from the database that matches the id from each of your search result and paginate as usual.

To do it faster, you could just paginate straight from the Elasticsearch results. No need to touch/ search against id in your database again.

**Comment by freekmurze** [comment]
@tandasima gave the correct answer.
